services:

  demo-postgres-db:
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5433:5432

  demo-redis-db:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6380:6379'
